// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgxiqwrbduhuokttuquu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBneGlxd3JiZHVodW9rdHR1cXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MjQxOTQsImV4cCI6MjA4OTUwMDE5NH0.9F_k7gxhCiJxpqlqi34E0Ga2WwUANlC4vGJLe6ottOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});